
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake ..
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello_world
        path: build/hello_world
   
