
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake ..
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello_world
        path: build/hello_world
  create_release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      # Download artifacts from the previous job
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: hello_world
          path: build
      - uses: underwindfall/create-release-with-debugapk@v2.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          asset_path: "build/hello_world"
          asset_name: hello_world
          asset_content_type: application/zip
    
